version: "3.9"
services:
  db:
    image: postgres:16
    container_name: batch-postgres
    environment:
      POSTGRES_DB: batchdb
      POSTGRES_USER: batchuser
      POSTGRES_PASSWORD: batchpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U batchuser -d batchdb"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  pgdata:
