spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/batchdb
    username: batchuser
    password: batchpass
    driver-class-name: org.postgresql.Driver
  batch:
    jdbc:
      initialize-schema: always
  sql:
    init:
      # Run our own schema.sql to create the 'transactions' table
      mode: always

logging:
  level:
    root: INFO

app:
  input-file: classpath:transactions.csv
  report-file: ./reports/summary.txt